export const Data = [
  {
    name: "Test Whatsapp",
    region: "US",
    createdOn: 1672531199000,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: "https://via.placeholder.com/100",
  },
  {
    name: "Super Jewels Quest",
    region: "CA, FR",
    createdOn: 1675036800000,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Quest",
    image_url: "https://via.placeholder.com/100",
  },
  {
    name: "Candy Clash",
    region: "US, UK",
    createdOn: 1662807714999,
    price: "Price info of Candy Clash",
    csv: "Some CSV link for Candy Clash",
    report: "Some report link for Candy Clash",
    image_url: "Some image URL of the campaign",
  },
  {
    name: "Battle Royale X",
    region: "IN, AU",
    createdOn: 1662806715124,
    price: "Price info of Battle Royale X",
    csv: "Some CSV link for Battle Royale X",
    report: "Some report link for Battle Royale X",
    image_url: "Some image URL of the campaign",
  },
  {
    name: "Puzzle Kingdom",
    region: "FR, DE",
    createdOn: 1662806711124,
    price: "Price info of Puzzle Kingdom",
    csv: "Some CSV link for Puzzle Kingdom",
    report: "Some report link for Puzzle Kingdom",
    image_url: "Some image URL of the campaign",
  },
  {
    name: "Racing Thunder",
    region: "JP",
    createdOn: 1662806680124,
    price: "Price info of Racing Thunder",
    csv: "Some CSV link for Racing Thunder",
    report: "Some report link for Racing Thunder",
    image_url: "Some image URL of the campaign",
  },
];
